version: "3.9" 
services:
  ganache:
    image: trufflesuite/ganache-cli
    command: --db=/data -e=150 --mnemonic "test test test" --account_keys_path=/data/key.json
    ports:
      - "8545:8545"
    volumes:
      - "./data:/data"